name: $(Date:yyyyMMdd)$(Rev:.r)

trigger:
  branches:
    include:
      - main
pr: none

resources:
  repositories:
    - repository: templates
      type: github
      name: microsoft/vscode-engineering
      ref: main
      endpoint: Monaco

parameters:
  - name: publishExtension
    # allow-any-unicode-next-line
    displayName: 🚀 Publish Extension
    type: boolean
    default: false

extends:
  template: azure-pipelines/extension/stable.yml@templates
  parameters:
    l10nSourcePaths: ./src
    customNPMRegistry: ''

    buildSteps:
      - script: yarn install --frozen-lockfile --check-files
        displayName: Install dependencies
        retryCountOnTaskFailure: 3

      - script: yarn run bundle
        displayName: Compile

    testSteps:
      - script: yarn install --frozen-lockfile --check-files
        displayName: Install dependencies
        retryCountOnTaskFailure: 3

      - script: yarn run bundle
        displayName: Compile

      - bash: |
          /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
          echo ">>> Started xvfb"
        displayName: Start xvfb

      - script: yarn run test
        displayName: Run test suite
        env:
          DISPLAY: ':99.0'
          TEST_JUNIT_XML_PATH: $(Agent.HomeDirectory)/test-results.xml

      # - script: yarn run browsertest --browserType=chromium
      #   displayName: Run test suite (chromium)
      #   env:
      #     TEST_JUNIT_XML_PATH: $(Agent.HomeDirectory)/browser-chromium-test-results.xml

      # - script: yarn run browsertest --browserType=firefox
      #   displayName: Run test suite (firefox)
      #   env:
      #     TEST_JUNIT_XML_PATH: $(Agent.HomeDirectory)/browser-firefox-test-results.xml

      # - script: yarn run browsertest --browserType=webkit
      #   displayName: Run test suite (webkit)
      #   env:
      #     TEST_JUNIT_XML_PATH: $(Agent.HomeDirectory)/browser-webkit-test-results.xml

    tsa:
      enabled: true
      options:
        codebaseName: 'devdiv_$(Build.Repository.Name)'
        serviceTreeID: '1788a767-5861-45fb-973b-c686b67c5541'
        instanceUrl: 'https://devdiv.visualstudio.com/defaultcollection'
        projectName: 'DevDiv'
        areaPath: "DevDiv\\VS Code (compliance tracking only)\\Visual Studio Code Web Extensions"
        notificationAliases:
          - 'stbatt@microsoft.com'
          - 'lszomoru@microsoft.com'
          - 'alros@microsoft.com'

    publishExtension: ${{ and(parameters.publishExtension, eq(variables['Build.Repository.Uri'], 'https://github.com/microsoft/vscode-pull-request-github.git')) }}