# Run on a schedule
trigger: none
pr: none

schedules:
  - cron: '0 9 * * Mon-Thu'
    displayName: Nightly Release Schedule
    always: true
    branches:
      include:
        - main

jobs:
  - job: nightly_release
    displayName: Nightly Release
    pool:
      name: Hosted macOS
    steps:
      - template: scripts/ci/common-setup.yml

      - task: ComponentGovernanceComponentDetection@0
        inputs:
          scanType: 'Register'
          verbosity: 'Verbose'
          alertWarningLevel: 'High'

      - script: yarn run test
        displayName: Run test suite
        env:
          TEST_JUNIT_XML_PATH: $(Agent.HomeDirectory)/test-results.xml

      - script: yarn run browsertest
        displayName: Run test suite (browser)
        env:
          TEST_JUNIT_XML_PATH: $(Agent.HomeDirectory)/browser-test-results.xml

      - script: >
          node ./scripts/prepare-nightly-build.js
          -v "$VERSION" -i "$NAME" -n "$DISPLAYNAME" -d "$DESCRIPTION" -p "$PUBLISHER"
        displayName: Generate package.json
        env:
          NAME: vscode-pull-request-github-insiders
          DISPLAYNAME: GitHub Pull Request Nightly Build
          DESCRIPTION: Nightly Build GitHub Pull Request extension
          PUBLISHER: GitHub

      - script: |
          mv ./package.json ./package.json.bak
          mv ./package.insiders.json ./package.json
          mv ./README.md ./README.md.bak
          mv ./README.insiders.md ./README.md
          mv ./src/constants.ts ./src/constants.ts.bak
          mv ./src/constants.insiders.ts ./src/constants.ts
          npx vsce publish -p "$TOKEN" --yarn --noVerify
        displayName: Publish
        env:
          TOKEN: $(vsce.token)
