# /*---------------------------------------------------------------------------------------------
#  *  Copyright (c) Microsoft Corporation. All rights reserved.
#  *  Licensed under the MIT License. See License.txt in the project root for license information.
#  *--------------------------------------------------------------------------------------------*/

#import "./queriesShared.gql"

fragment Node on Node {
	id
}

fragment Actor on Actor  { # We don't want to reference Bot because it is not available on older GHE, so we use Actor instead as it gets us most of the way there.
	__typename
	login
	avatarUrl
	url
}

fragment User on User {
	__typename
	...Actor
	email
	name
	...Node
}

fragment Organization on Organization {
	__typename
	...Actor
	email
	name
	...Node
}

fragment Reactable on Reactable {
	reactionGroups {
		content
		viewerHasReacted
		reactors(first: 10) {
			nodes {
				... on User {
					login
				}
				... on Actor {
					login
				}
			}
			totalCount
		}
	}
}

fragment IssueBase on Issue {
	number
	url
	state
	body
	bodyHTML
	title
	titleHTML
	author {
		...Node
		...Actor
		...User
		...Organization
	}
	createdAt
	updatedAt
	milestone {
		title
		dueOn
		createdAt
		id
		number
	}
	assignees(first: 10) {
		nodes {
			...Node
			...Actor
			...User
		}
	}
	labels(first: 50) {
		nodes {
			name
			color
		}
	}
	id
	databaseId
	reactions(first: 100) {
		totalCount
	}
	...Reactable
	repository {
		name
		owner {
			login
		}
		url
	}
}

fragment IssueFragment on Issue {
	...IssueBase
	comments(first: 1) {
		totalCount
	}
}

fragment IssueWithCommentsFragment on Issue {
	...IssueBase
	comments(first: 50) {
		nodes {
			author {
				...Node
				...Actor
				...User
				...Organization
			}
			body
			databaseId
			reactions(first: 100) {
				totalCount
			}
		}
		totalCount
	}
}

fragment PullRequestFragment on PullRequest {
	number
	url
	state
	body
	bodyHTML
	title
	titleHTML
	author {
		...Node
		...Actor
		...User
		...Organization
	}
	createdAt
	updatedAt
	milestone {
		title
		dueOn
		createdAt
		id
		number
	}
	assignees(first: 10) {
		nodes {
			...Node
			...Actor
			...User
		}
	}
	labels(first: 50) {
		nodes {
			name
			color
		}
	}
	id
	databaseId
	reactions(first: 100) {
		totalCount
	}
	...Reactable
	comments(first: 1) {
		totalCount
	}

	commits(first: 50) {
		nodes {
			commit {
				message
			}
		}
	}
	headRef {
		...Ref
	}
	headRefName
	headRefOid
	headRepository {
		isInOrganization
		owner {
			login
		}
		url
	}
	baseRef {
		...Ref
	}
	baseRefName
	baseRefOid
	baseRepository {
		isInOrganization
		owner {
			login
		}
		url
	}
	merged
	mergeable
	mergeStateStatus
	autoMergeRequest {
		mergeMethod
	}
	reviewThreads {
		totalCount
	}
	viewerCanEnableAutoMerge
	viewerCanDisableAutoMerge
	viewerCanUpdate
	isDraft
	suggestedReviewers {
		isAuthor
		isCommenter
		reviewer {
			...Actor
			...User
			...Node
		}
	}
}

query Issue($owner: String!, $name: String!, $number: Int!) {
	repository(owner: $owner, name: $name) {
		issue(number: $number) {
			...IssueFragment
		}
	}
	rateLimit {
		...RateLimit
	}
}

query IssueWithComments($owner: String!, $name: String!, $number: Int!) {
	repository(owner: $owner, name: $name) {
		issue(number: $number) {
			...IssueWithCommentsFragment
		}
	}
	rateLimit {
		...RateLimit
	}
}

query Issues($query: String!) {
	search(first: 100, type: ISSUE, query: $query) {
		issueCount
		pageInfo {
			hasNextPage
			endCursor
		}
		edges {
			node {
				...IssueFragment
			}
		}
	}
	rateLimit {
		...RateLimit
	}
}

query PullRequest($owner: String!, $name: String!, $number: Int!) {
	repository(owner: $owner, name: $name) {
		pullRequest(number: $number) {
			...PullRequestFragment
		}
	}
	rateLimit {
		...RateLimit
	}
}

query PullRequestForHead($owner: String!, $name: String!, $headRefName: String!) {
	repository(owner: $owner, name: $name) {
		pullRequests(first: 3, headRefName: $headRefName, orderBy: { field: CREATED_AT, direction: DESC }) {
			nodes {
				...PullRequestFragment
			}
		}
	}
	rateLimit {
		...RateLimit
	}
}

query GetAssignableUsers($owner: String!, $name: String!, $first: Int!, $after: String) {
	repository(owner: $owner, name: $name) {
		assignableUsers(first: $first, after: $after) {
			nodes {
				...User
			}
			pageInfo {
				hasNextPage
				endCursor
			}
		}
	}
	rateLimit {
		...RateLimit
	}
}

mutation CreatePullRequest($input: CreatePullRequestInput!) {
	createPullRequest(input: $input) {
		pullRequest {
			...PullRequestFragment
		}
	}
}

mutation RevertPullRequest($input: RevertPullRequestInput!) {
	revertPullRequest(input: $input) {
		revertPullRequest {
			...PullRequestFragment
		}
	}
}
