# /*---------------------------------------------------------------------------------------------
#  *  Copyright (c) Microsoft Corporation. All rights reserved.
#  *  Licensed under the MIT License. See License.txt in the project root for license information.
#  *--------------------------------------------------------------------------------------------*/

#import "./queriesShared.gql"

fragment Node on Node {
	id
}

fragment Actor on Actor  { # We don't want to reference Bot because it is not available on older GHE, so we use Actor instead as it gets us most of the way there.
	__typename
	login
	avatarUrl
	url
}

fragment User on User {
	__typename
	...Actor
	email
	name
	...Node
}

fragment Organization on Organization {
	__typename
	...Actor
	email
	name
	...Node
}

fragment PullRequestFragment on PullRequest {
	number
	url
	state
	body
	bodyHTML
	titleHTML
	title
	author {
		...User
		...Organization
	}
	commits(first: 50) {
		nodes {
			commit {
				message
			}
		}
	}
	createdAt
	updatedAt
	headRef {
		...Ref
	}
	headRefName
	headRefOid
	headRepository {
		isInOrganization
		owner {
			login
		}
		url
	}
	baseRef {
		...Ref
	}
	baseRefName
	baseRefOid
	baseRepository {
		isInOrganization
		owner {
			login
		}
		url
	}
	labels(first: 50) {
		nodes {
			name
			color
		}
	}
	merged
	mergeable
	mergeStateStatus
	autoMergeRequest {
		mergeMethod
	}
	reviewThreads {
		totalCount
	}
	viewerCanEnableAutoMerge
	viewerCanDisableAutoMerge
	viewerCanUpdate
	id
	databaseId
	isDraft
	milestone {
		title
		dueOn
		createdAt
		id
		number
	}
	assignees(first: 10) {
		nodes {
			...User
		}
	}
	suggestedReviewers {
		isAuthor
		isCommenter
		reviewer {
			...User
			...Actor
			...Node
		}
	}
	reactions(first: 1) {
		totalCount
	}
	comments(first: 1) {
		totalCount
	}
}

query PullRequest($owner: String!, $name: String!, $number: Int!) {
	repository(owner: $owner, name: $name) {
		pullRequest(number: $number) {
			...PullRequestFragment
		}
	}
	rateLimit {
		...RateLimit
	}
}


query PullRequestForHead($owner: String!, $name: String!, $headRefName: String!) {
	repository(owner: $owner, name: $name) {
		pullRequests(first: 3, headRefName: $headRefName, orderBy: { field: CREATED_AT, direction: DESC }) {
			nodes {
				...PullRequestFragment
			}
		}
	}
	rateLimit {
		...RateLimit
	}
}


mutation CreatePullRequest($input: CreatePullRequestInput!) {
	createPullRequest(input: $input) {
		pullRequest {
			...PullRequestFragment
		}
	}
}

mutation RevertPullRequest($input: RevertPullRequestInput!) {
	revertPullRequest(input: $input) {
		revertPullRequest {
			...PullRequestFragment
		}
	}
}
