# /*---------------------------------------------------------------------------------------------
#  *  Copyright (c) Microsoft Corporation. All rights reserved.
#  *  Licensed under the MIT License. See License.txt in the project root for license information.
#  *--------------------------------------------------------------------------------------------*/

#import "./queriesShared.gql"

fragment PullRequestFragment on PullRequest {
	number
	url
	state
	body
	bodyHTML
	titleHTML
	title
	author {
		login
		url
		avatarUrl
		... on User {
			email
			id
		}
		... on Organization {
			email
			id
		}
	}
	commits(first: 50) {
		nodes {
			commit {
				message
			}
		}
	}
	createdAt
	updatedAt
	headRef {
		...Ref
	}
	headRefName
	headRefOid
	headRepository {
		isInOrganization
		owner {
			login
		}
		url
	}
	baseRef {
		...Ref
	}
	baseRefName
	baseRefOid
	baseRepository {
		isInOrganization
		owner {
			login
		}
		url
	}
	labels(first: 50) {
		nodes {
			name
			color
		}
	}
	merged
	mergeable
	mergeStateStatus
	autoMergeRequest {
		mergeMethod
	}
	viewerCanEnableAutoMerge
	viewerCanDisableAutoMerge
	viewerCanUpdate
	id
	databaseId
	isDraft
	milestone {
		title
		dueOn
		createdAt
		id
		number
	}
	assignees(first: 10) {
		nodes {
			login
			name
			avatarUrl
			id
			url
			email
		}
	}
	suggestedReviewers {
		isAuthor
		isCommenter
		reviewer {
			login
			avatarUrl
			id
			name
			url
		}
	}
}

query PullRequest($owner: String!, $name: String!, $number: Int!) {
	repository(owner: $owner, name: $name) {
		pullRequest(number: $number) {
			...PullRequestFragment
		}
	}
	rateLimit {
		...RateLimit
	}
}


query PullRequestForHead($owner: String!, $name: String!, $headRefName: String!) {
	repository(owner: $owner, name: $name) {
		pullRequests(first: 3, headRefName: $headRefName, orderBy: { field: CREATED_AT, direction: DESC }) {
			nodes {
				...PullRequestFragment
			}
		}
	}
	rateLimit {
		...RateLimit
	}
}

mutation CreatePullRequest($input: CreatePullRequestInput!) {
	createPullRequest(input: $input) {
		pullRequest {
			...PullRequestFragment
		}
	}
}