# /*---------------------------------------------------------------------------------------------
#  *  Copyright (c) Microsoft Corporation. All rights reserved.
#  *  Licensed under the MIT License. See License.txt in the project root for license information.
#  *--------------------------------------------------------------------------------------------*/

fragment Comment on PullRequestReviewComment {
	id databaseId url
	author { login avatarUrl }
	path originalPosition
	body
	diffHunk
	position
	state
	pullRequestReview { databaseId }
}

query GetPendingReviewId($pullRequestId: ID!, $author: String!) {
	node(id: $pullRequestId) {
		...on PullRequest {
			reviews(first: 1, author: $author, states: [PENDING]) { nodes { id } }
		}
	}
}

query PullRequestComments($owner:String!, $name:String!, $number:Int!, $first:Int=100) {
	repository(owner:$owner, name:$name) {
		pullRequest(number:$number) {
			reviews(first:$first) {
				nodes {
					comments(first:100) {
						nodes { ...Comment }
					}
				}
			}
		}
	}
}

query GetMentionableUsers($owner: String!, $name: String!, $first: Int!, $after: String) {
	repository(owner: $owner, name: $name) {
		mentionableUsers(first: $first, after: $after) {
			nodes {
				login
				avatarUrl
				name
			}
			pageInfo {
				hasNextPage
				endCursor
			}
		}
	}
}


mutation AddComment($input: AddPullRequestReviewCommentInput!) {
	addPullRequestReviewComment(input: $input) {
		comment {
		...Comment
		}
	}
}

mutation StartReview($input: AddPullRequestReviewInput!) {
	addPullRequestReview(input: $input) {
		pullRequestReview { id }
	}
}

mutation SubmitReview($id: ID!) {
	submitPullRequestReview(input: {
		event: COMMENT,
		pullRequestReviewId: $id
	}) {
		pullRequestReview {
			comments(first:100) {
				nodes { ...Comment }
			}
		}
	}
}

mutation DeleteReview($input: DeletePullRequestReviewInput!) {
	deletePullRequestReview(input: $input) {
		pullRequestReview {
			comments(first:100) {
					nodes { ...Comment }
			}
		}
	}
}