import * as REST from '@octokit/rest';
import { Builder } from 'builder-pattern';
import { createRESTUser } from './userBuilder';

const templateRESTRepo: REST.PullRequestsGetResponseHeadRepo | REST.PullRequestsGetAllResponseItemBaseRepo = {
	id: 0,
	node_id: 'node0',
	name: 'reponame',
	full_name: 'octocat/reponame',
	description: 'The default repo',
	owner: createRESTUser().build(),
	private: false,
	fork: false,
	url: 'https://api.github.com/repos/octocat/reponame',
	html_url: 'https://github.com/octocat/reponame',
	archive_url: 'http://api.github.com/repos/octocat/reponame/{archive_format}{/ref}',
	assignees_url: 'http://api.github.com/repos/octocat/reponame/assignees{/user}',
	blobs_url: 'http://api.github.com/repos/octocat/reponame/git/blobs{/sha}',
	branches_url: 'http://api.github.com/repos/octocat/reponame/branches{/branch}',
	collaborators_url: 'http://api.github.com/repos/octocat/reponame/collaborators{/collaborator}',
	comments_url: 'http://api.github.com/repos/octocat/reponame/comments{/number}',
	commits_url: 'http://api.github.com/repos/octocat/reponame/commits{/sha}',
	compare_url: 'http://api.github.com/repos/octocat/reponame/compare/{base}...{head}',
	contents_url: 'http://api.github.com/repos/octocat/reponame/contents/{+path}',
	contributors_url: 'http://api.github.com/repos/octocat/reponame/contributors',
	deployments_url: 'http://api.github.com/repos/octocat/reponame/deployments',
	downloads_url: 'http://api.github.com/repos/octocat/reponame/downloads',
	events_url: 'http://api.github.com/repos/octocat/reponame/events',
	forks_url: 'http://api.github.com/repos/octocat/reponame/forks',
	git_commits_url: 'http://api.github.com/repos/octocat/reponame/git/commits{/sha}',
	git_refs_url: 'http://api.github.com/repos/octocat/reponame/git/refs{/sha}',
	git_tags_url: 'http://api.github.com/repos/octocat/reponame/git/tags{/sha}',
	git_url: 'git:github.com/octocat/reponame.git',
	issue_comment_url: 'http://api.github.com/repos/octocat/reponame/issues/comments{/number}',
	issue_events_url: 'http://api.github.com/repos/octocat/reponame/issues/events{/number}',
	issues_url: 'http://api.github.com/repos/octocat/reponame/issues{/number}',
	keys_url: 'http://api.github.com/repos/octocat/reponame/keys{/key_id}',
	labels_url: 'http://api.github.com/repos/octocat/reponame/labels{/name}',
	languages_url: 'http://api.github.com/repos/octocat/reponame/languages',
	merges_url: 'http://api.github.com/repos/octocat/reponame/merges',
	milestones_url: 'http://api.github.com/repos/octocat/reponame/milestones{/number}',
	notifications_url: 'http://api.github.com/repos/octocat/reponame/notifications{?since,all,participating}',
	pulls_url: 'http://api.github.com/repos/octocat/reponame/pulls{/number}',
	releases_url: 'http://api.github.com/repos/octocat/reponame/releases{/id}',
	ssh_url: 'git@github.com:octocat/reponame.git',
	stargazers_url: 'http://api.github.com/repos/octocat/reponame/stargazers',
	statuses_url: 'http://api.github.com/repos/octocat/reponame/statuses/{sha}',
	subscribers_url: 'http://api.github.com/repos/octocat/reponame/subscribers',
	subscription_url: 'http://api.github.com/repos/octocat/reponame/subscription',
	tags_url: 'http://api.github.com/repos/octocat/reponame/tags',
	teams_url: 'http://api.github.com/repos/octocat/reponame/teams',
	trees_url: 'http://api.github.com/repos/octocat/reponame/git/trees{/sha}',
	clone_url: 'https://github.com/octocat/reponame.git',
	mirror_url: 'git:git.example.com/octocat/reponame',
	hooks_url: 'http://api.github.com/repos/octocat/reponame/hooks',
	svn_url: 'https://svn.github.com/octocat/reponame',
	homepage: 'https://github.com',
	language: null,
	forks_count: 9,
	stargazers_count: 80,
	watchers_count: 80,
	size: 108,
	default_branch: 'master',
	open_issues_count: 0,
	topics: [],
	has_issues: true,
	has_projects: true,
	has_wiki: true,
	has_pages: false,
	has_downloads: true,
	archived: false,
	pushed_at: '2011-01-26T19:06:43Z',
	created_at: '2011-01-26T19:01:12Z',
	updated_at: '2011-01-26T19:14:43Z',
	permissions: {
		admin: false,
		push: false,
		pull: true
	},
	allow_rebase_merge: true,
	allow_squash_merge: true,
	allow_merge_commit: true,
	subscribers_count: 42,
	network_count: 0
};

export function createRESTRepo() {
	return Builder(templateRESTRepo);
}